RothersStaticBundle:
    resource: "@PortfolioBundle/Controller/"
    type:     annotation
    prefix:   /
UserBundle:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
ContactBundle:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
