security:
    providers:
      rothers_user:
        entity: { class: UserExtensionBundle:User }
            
    encoders:
      Rothers\UserBundle\Entity\User:
        algorithm: sha512
        encode_as_base64: false
        iterations: 1

    role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_AGENT, ROLE_CUSTOMER]

    firewalls:
      %security.firewall.name%:
        pattern:    ^/
        form_login:
          provider: rothers_user
        logout: true
        anonymous: true

    access_control:
      - { path: ^/admin/, role: ROLE_ADMIN }
